name: drlnd-continuous-control
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=18.1
  - python=3.6.7
  - pip:
    - matplotlib==3.0.2
    - numpy==1.15.4
    - pandas==0.23.4
    - scipy==1.2.0
    - torch==0.4.0
    - unityagents==0.4.0

